name: build and run tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '15']
        db: ['mysql:5.7.35', 'mysql:8.0', 'mariadb:10.3', 'mariadb:10.5']
    services:
      mysql:
        image: ${{ matrix.db }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java ${{ matrix.Java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE stevedb_test_2aa6a783d47d;"
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE USER 'steve'@'localhost' IDENTIFIED BY 'changeme';"
          mysql -h 127.0.0.1 -uroot -proot -e "GRANT ALL PRIVILEGES ON stevedb_test_2aa6a783d47d.* TO 'steve'@'localhost';"
          mysql -h 127.0.0.1 -uroot -proot -e "GRANT SELECT ON mysql.proc TO 'steve'@'localhost';"
          mysql -h 127.0.0.1 -uroot -proot -e "GRANT SUPER ON *.* TO 'steve'@'localhost';"
      - name: Build with Maven
        run: mvn -B -V -Dmaven.javadoc.skip=true -Ptest clean package --file pom.xml
